version: "2.0"

services:
  backend:
    image: eb1609/albania-backend:latest
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
    env:
      - GROQ_API_KEY=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
      - GOOGLE_PLACES_API_KEY=AIzaSyAezZ520c39xtnHgo43xmMV6z9eY8R6npg

  frontend:
    image: eb1609/albania-frontend:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    backend-profile:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 2Gi
    frontend-profile:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi

  placement:
    dcloud:
      pricing:
        backend-profile:
          denom: uakt
          amount: 1000
        frontend-profile:
          denom: uakt
          amount: 1000

deployment:
  backend:
    dcloud:
      profile: backend-profile
      count: 1
  frontend:
    dcloud:
      profile: frontend-profile
      count: 1